<a href="https://colab.research.google.com/github/jayjinnie/gbdcon/blob/main/%EA%B2%BD%EB%B6%81_%EA%B5%AC%EB%A7%A4_%EC%9D%B4%EB%A0%A5_%EA%B8%B0%EB%B0%98_%EC%9E%A0%EC%9E%AC_%EC%9A%94%EC%9D%B8_%ED%98%91%EC%97%85_%ED%95%84%ED%84%B0%EB%A7%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 고객의 구매 이력을 기반으로 맞춤형 상품을 추천하는 시스템

# pivot 테이블 만들기
#### 고객-상품 선호도 데이터를 pivot 테이블로 변환

In [ ]:
import pandas as pd
df_ratings = pd.read_csv("선호도 테이블.csv")
df_ratings

회원번호        상품코드         선호도
0           1  1586858861   18.680282
1           1  1602651612   27.532331
2           1  1594681077  146.906185
3           1  1601251488   20.818027
4           1  1601251488   20.818027
...       ...         ...         ...
16457  169279  1601971908   27.192747
16458  169280  1601972061   28.672495
16459  169282  1585032127   16.827011
16460  169286  1581252441   15.120096
16461  169295  1606736503   31.949611

[16462 rows x 3 columns]

In [ ]:
df_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16462 entries, 0 to 16461
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   회원번호    16462 non-null  int64  
 1   상품코드    16462 non-null  int64  
 2   선호도     16462 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 386.0 KB


In [ ]:
df_merchandise = pd.read_excel("장바구니테이블.xlsx", header=1)
df_merchandise.head() 

장바구니번호                                               주문번호  ... 배송비  추가배송비
0  2079375  9a8c27650c828207d03dbb34fb5d17dbbd2452b602e829...  ...   0      0
1  2079381  5f6410d90f5f42b49efeebecee50a989aee88658569f52...  ...   0      0
2  2079385  1291ff3422b02515594f564eae65980860baa03bf55809...  ...   0      0
3  2079386  1291ff3422b02515594f564eae65980860baa03bf55809...  ...   0      0
4  2079399  063d48e1e8eb1a865670286467c6ccf8b6a3e62d1d35d3...  ...   0      0

[5 rows x 21 columns]

In [ ]:
df_merchandise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80186 entries, 0 to 80185
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   장바구니번호   80186 non-null  int64  
 1   주문번호     80186 non-null  object 
 2   회원아이디    80186 non-null  object 
 3   상품코드     80182 non-null  float64
 4   상품명      80186 non-null  object 
 5   상품 배송비   80186 non-null  int64  
 6   상품가격     80186 non-null  int64  
 7   포인트      80186 non-null  int64  
 8   쿠폰금액     80186 non-null  int64  
 9   주문옵션     73921 non-null  object 
 10  주문수량     80186 non-null  int64  
 11  옵션가격     80186 non-null  int64  
 12  업체ID     80186 non-null  object 
 13  즉시할인쿠폰   80186 non-null  int64  
 14  단골할인쿠폰   80186 non-null  int64  
 15  배송방법     80186 non-null  object 
 16  배송일      80186 non-null  object 
 17  배송완료예정일  80186 non-null  object 
 18  지원가격     80186 non-null  int64  
 19  배송비      80186 non-null  int64  
 20  추가배송비    80186 non-null  int64  
dtypes: float64(1

In [ ]:
df_custom_merc_ratings = df_ratings.pivot_table(
    index='회원번호', 
    columns='상품코드', 
    values='선호도'
).fillna(0)
df_custom_merc_ratings

상품코드    1577870016  1577933738  1577947433  ...  1608187426  1608600164  1608699587
회원번호                                        ...                                    
1              0.0         0.0         0.0  ...         0.0         0.0         0.0
60251          0.0         0.0         0.0  ...         0.0         0.0         0.0
60596          0.0         0.0         0.0  ...         0.0         0.0         0.0
60603          0.0         0.0         0.0  ...         0.0         0.0         0.0
60729          0.0         0.0         0.0  ...         0.0         0.0         0.0
...            ...         ...         ...  ...         ...         ...         ...
169279         0.0         0.0         0.0  ...         0.0         0.0         0.0
169280         0.0         0.0         0.0  ...         0.0         0.0         0.0
169282         0.0         0.0         0.0  ...         0.0         0.0         0.0
169286         0.0         0.0         0.0  ...         0.0         0.0         0.0
169295         0.0         0.0         0.0  ...         0.0         0.0         0.0

[8988 rows x 1590 columns]

# N명의 고객들이 M개의 상품에 매긴 각각의 평균 선호도 구하기
#### 이렇게 구한 평균 선호도 값을 고객-상품 선호도 값에서 빼기

In [ ]:
import numpy as np

# matrix는 pivot table값을 numpy matrix로 만든 것
matrix = df_custom_merc_ratings.values

# customer_ratings_mean은 고객의 평균 선호도
custom_ratings_mean = np.mean(matrix, axis=1)

# R_user_mean: 고객-상품에 대하여 고객 평균 선호도를 뺀 것
matrix_custom_mean = matrix - custom_ratings_mean.reshape(-1,1)

In [ ]:
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
matrix_custom_mean

array([[-0.27359344, -0.27359344, -0.27359344, ..., -0.27359344,
        -0.27359344, -0.27359344],
       [-0.07100404, -0.07100404, -0.07100404, ..., -0.07100404,
        -0.07100404, -0.07100404],
       [-0.08872174, -0.08872174, -0.08872174, ..., -0.08872174,
        -0.08872174, -0.08872174],
       ...,
       [-0.01058303, -0.01058303, -0.01058303, ..., -0.01058303,
        -0.01058303, -0.01058303],
       [-0.00950949, -0.00950949, -0.00950949, ..., -0.00950949,
        -0.00950949, -0.00950949],
       [-0.02009409, -0.02009409, -0.02009409, ..., -0.02009409,
        -0.02009409, -0.02009409]])

In [ ]:
pd.DataFrame(matrix_custom_mean, columns = df_custom_merc_ratings.columns)

상품코드  1577870016  1577933738  1577947433  ...  1608187426  1608600164  1608699587
0      -0.273593   -0.273593   -0.273593  ...   -0.273593   -0.273593   -0.273593
1      -0.071004   -0.071004   -0.071004  ...   -0.071004   -0.071004   -0.071004
2      -0.088722   -0.088722   -0.088722  ...   -0.088722   -0.088722   -0.088722
3      -0.023095   -0.023095   -0.023095  ...   -0.023095   -0.023095   -0.023095
4      -0.083072   -0.083072   -0.083072  ...   -0.083072   -0.083072   -0.083072
...          ...         ...         ...  ...         ...         ...         ...
8983   -0.017102   -0.017102   -0.017102  ...   -0.017102   -0.017102   -0.017102
8984   -0.018033   -0.018033   -0.018033  ...   -0.018033   -0.018033   -0.018033
8985   -0.010583   -0.010583   -0.010583  ...   -0.010583   -0.010583   -0.010583
8986   -0.009509   -0.009509   -0.009509  ...   -0.009509   -0.009509   -0.009509
8987   -0.020094   -0.020094   -0.020094  ...   -0.020094   -0.020094   -0.020094

[8988 rows x 1590 columns]

# SVD (Singular Value Decomposition, 특이값 분해)를 이용한 잠재 요인 협업 필터링 (Latent Factor Collaborative Filtering)
#### mxn 크기의 A 행렬을 mxm 크기의 U 행렬, mxn 크기의 sigma k 행렬, nxn 크기의 Vt 행렬로 분해한 뒤, 대각 성분(A 행렬의 특이값) 중 상위 p개를 추출하기
#### 원 행렬로 100% 복원할 수는 없으나 기존의 A 행렬과 거의 근사한 값을 추출할 수 있음

In [ ]:
from scipy.sparse.linalg import svds
from scipy.linalg import svd

U, sigma, Vt = svds(matrix_custom_mean, k=12)
print(U.shape)
print(sigma.shape)
print(Vt.shape)

(8988, 12)
(12,)
(12, 1590)


In [ ]:
sigma = np.diag(sigma)
sigma.shape

(12, 12)

In [ ]:
sigma[0]

array([3080.53931685,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ])

In [ ]:
sigma[1]

array([   0.        , 3625.64183027,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ])

#### U, Sigma, Vt의 내적을 수행, 고객의 선호도 평균을 더하여 원본 행렬로 복구한 뒤, 이 행렬에 고객 평균 선호도를 적용하기

In [ ]:
svd_custom_pred_ratings = np.dot(np.dot(U, sigma), Vt) + custom_ratings_mean.reshape(-1,1)

In [ ]:
df_svd_preds = pd.DataFrame(svd_custom_pred_ratings, columns = df_custom_merc_ratings.columns)
df_svd_preds

상품코드  1577870016  1577933738  1577947433  ...  1608187426  1608600164  1608699587
0       0.277008    0.277001    0.276990  ...    0.275879    0.277007    0.276709
1       0.071255    0.071255    0.071256  ...    0.071282    0.071255    0.071255
2       0.089616    0.089614    0.089611  ...    0.089204    0.089616    0.089726
3       0.023322    0.023321    0.023321  ...    0.023229    0.023322    0.023319
4       0.082882    0.082884    0.082888  ...    0.083167    0.082882    0.082970
...          ...         ...         ...  ...         ...         ...         ...
8983    0.017305    0.017305    0.017304  ...    0.017233    0.017305    0.017296
8984    0.018146    0.018146    0.018146  ...    0.018140    0.018146    0.018135
8985    0.010715    0.010714    0.010714  ...    0.010671    0.010715    0.010703
8986    0.009618    0.009618    0.009618  ...    0.009585    0.009618    0.009608
8987    0.020344    0.020343    0.020342  ...    0.020262    0.020344    0.020322

[8988 rows x 1590 columns]

#### SVD 특이값 분해를 사용하여 행렬분해를 기반으로 데이터 변형 완료

# 고객 구매 이력을 기반으로 가장 연관성이 높은 상품을 추천하는 함수 만들기
#### 인자로 회원 정보, 상품 정보, 선호도 등을 받음
#### 회원 정보에 SVD로 나온 결과의 상품 선호도가 가장 높은 데이터 순으로 정렬
#### 고객이 구매한 상품을 제외
#### 고객이 구매하지 않은 상품 중 유사한 선호도를 지닌 상품을 추천

In [ ]:
customer_row_number = df_ratings.회원번호

In [ ]:
len(df_svd_preds.reset_index()["index"])

8988

In [ ]:
df_svd_preds.set_index("회원번호",inplace=True)

In [ ]:
df_svd_preds

상품코드  1577870016  1577933738  1577947433  ...  1608187426  1608600164  1608699587
0       0.277008    0.277001    0.276990  ...    0.275879    0.277007    0.276709
1       0.071255    0.071255    0.071256  ...    0.071282    0.071255    0.071255
2       0.089616    0.089614    0.089611  ...    0.089204    0.089616    0.089726
3       0.023322    0.023321    0.023321  ...    0.023229    0.023322    0.023319
4       0.082882    0.082884    0.082888  ...    0.083167    0.082882    0.082970
...          ...         ...         ...  ...         ...         ...         ...
8983    0.017305    0.017305    0.017304  ...    0.017233    0.017305    0.017296
8984    0.018146    0.018146    0.018146  ...    0.018140    0.018146    0.018135
8985    0.010715    0.010714    0.010714  ...    0.010671    0.010715    0.010703
8986    0.009618    0.009618    0.009618  ...    0.009585    0.009618    0.009608
8987    0.020344    0.020343    0.020342  ...    0.020262    0.020344    0.020322

[8988 rows x 1590 columns]

In [ ]:
def recommend_merchandise(df_svd_preds, customer_id, ori_merc_df, ori_ratings_df, num_recommendations):

  # 최종적으로 만든 pred_df에서 고객 index에 따라 상품 데이터 정렬하기 -> 상품 선호도가 높은 순으로 정렬됨
  sorted_customer_pred=df_svd_preds.loc[df_svd_preds["회원번호"]==customer_id].set_index("회원번호").transpose().sort_values(by=customer_id,ascending=False).transpose()

  # 원본 선호도 데이터에서 회원번호에 해당하는 데이터 추출
  customer_data = df_ratings[df_ratings["회원번호"]==customer_id]

  # 추출한 회원 데이터와 원본 상품 데이터를 합침
  customer_history = customer_data.merge(df_merchandise, on='상품코드').sort_values(['선호도'], ascending=False)

  # 원본 상품 데이터에서 고객이 구매한 상품을 제외한 데이터를 추출
  recommendations = df_merchandise[~df_merchandise['상품코드'].isin(customer_history['상품코드'])]

  # 고객의 선호도가 높은 순으로 정렬된 데이터와, 위의 recommendation 데이터를 합침
  recommendations = recommendations.merge(pd.DataFrame(sorted_customer_pred.transpose()).reset_index(), on='상품코드')
 
  # 고객의 선호도가 높은 순으로 정렬된 데이터와, 위의 recommendation 데이터를 합침
  recommendations = recommendations.rename(columns={customer_id:"추천 예상"}).sort_values(by="추천 예상",ascending=False).head(num_recommendations)

  return customer_history, recommendations

In [ ]:
pd.DataFrame(sorted_customer_pred.transpose()).reset_index().rename(columns={customer_id:"선호도"}

회원번호        상품코드     60251
0     1592373538  0.100504
1     1595904905  0.096348
2     1589126164  0.084821
3     1588214366  0.079791
4     1593673443  0.075282
...          ...       ...
1585  1603865613  0.010386
1586  1604385982  0.002753
1587  1584201031  0.002247
1588  1606464566 -0.002416
1589  1582691001 -0.006119

[1590 rows x 2 columns]

In [ ]:
df_merchandise[~df_merchandise['상품코드'].isin(customer_history['상품코드'])]

장바구니번호                                               주문번호  ...   배송비  추가배송비
0      2079375  9a8c27650c828207d03dbb34fb5d17dbbd2452b602e829...  ...     0      0
1      2079381  5f6410d90f5f42b49efeebecee50a989aee88658569f52...  ...     0      0
2      2079385  1291ff3422b02515594f564eae65980860baa03bf55809...  ...     0      0
3      2079386  1291ff3422b02515594f564eae65980860baa03bf55809...  ...     0      0
4      2079399  063d48e1e8eb1a865670286467c6ccf8b6a3e62d1d35d3...  ...     0      0
...        ...                                                ...  ...   ...    ...
80181  2699790  370c05718f52e6003a13545d4a81d1fce5a6d8aee63f1b...  ...     0      0
80182  2699791  e61f1b8ef6c010b68f6d3284a3a4fbb558158fd75b4c40...  ...  3000      0
80183  2699792  d7e14150e95b27de2684eb5d7d15f0d5ffe474f8d2e379...  ...     0      0
80184  2699794  8c20d4ce58aa68ad95478671e105837a82940861cf124a...  ...     0      0
80185  2699795  ca091ccccc6a4d46c1240580eb43dade3393b3c52bc28c...  ...     0      0

[80107 rows x 21 columns]

In [ ]:
customer_history

회원번호        상품코드        선호도  ...  지원가격 배송비 추가배송비
39  60251  1604964672  52.623073  ...  6300   0     0
28  60251  1604964672  52.623073  ...  6300   0     0
30  60251  1604964672  52.623073  ...  6300   0     0
32  60251  1604964672  52.623073  ...  6300   0     0
33  60251  1604964672  52.623073  ...  6300   0     0
..    ...         ...        ...  ...   ...  ..   ...
1   60251  1600146749  17.054424  ...     0   0     0
4   60251  1600146749  17.054424  ...     0   0     0
3   60251  1600146749  17.054424  ...     0   0     0
2   60251  1600146749  17.054424  ...     0   0     0
0   60251  1600146749  17.054424  ...     0   0     0

[79 rows x 23 columns]

In [ ]:
recommendations

장바구니번호  ...     60251
0      2087111  ...  0.071302
1      2087115  ...  0.071289
2      2088937  ...  0.071255
3      2089114  ...  0.071255
4      2128141  ...  0.071255
...        ...  ...       ...
23783  2698829  ...  0.071254
23784  2699129  ...  0.071254
23785  2698936  ...  0.071262
23786  2699533  ...  0.071255
23787  2699614  ...  0.071255

[23788 rows x 22 columns]

In [ ]:
sorted_customer_pred.transpose().reset_index()["상품코드"]

0       1592373538
1       1595904905
2       1589126164
3       1588214366
4       1593673443
           ...    
1585    1603865613
1586    1604385982
1587    1584201031
1588    1606464566
1589    1582691001
Name: 상품코드, Length: 1590, dtype: int64

In [ ]:
df_svd_preds.reset_index(inplace=True)

In [ ]:
df_svd_preds["회원번호"]

0            1
1        60251
2        60596
3        60603
4        60729
         ...  
8983    169279
8984    169280
8985    169282
8986    169286
8987    169295
Name: 회원번호, Length: 8988, dtype: int64

In [ ]:
# 회원번호 1인 고객이 행렬 분해 기반의 추천 시스템으로부터 받은 추천 상품 목록
num_recommendations = 5
customer_id = 60729


# 고객 구매이력, 선호도
already_rated,prediction= recommend_merchandise(df_svd_preds, customer_id, df_merchandise, df_ratings, num_recommendations)

In [ ]:
already_rated

회원번호        상품코드        선호도  ...  지원가격 배송비 추가배송비
0   60729  1598427460  57.537618  ...     0   0     0
37  60729  1598427460  57.537618  ...     0   0     0
53  60729  1598427460  57.537618  ...     0   0     0
52  60729  1598427460  57.537618  ...     0   0     0
51  60729  1598427460  57.537618  ...     0   0     0
..    ...         ...        ...  ...   ...  ..   ...
76  60729  1602486335  19.340911  ...  5040   0     0
77  60729  1602486335  19.340911  ...  5040   0     0
78  60729  1602486335  19.340911  ...  5040   0     0
79  60729  1602486335  19.340911  ...  7650   0     0
80  60729  1602486335  19.340911  ...  7650   0     0

[161 rows x 23 columns]